# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_auto_20180910_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=6),
        ),
    ]
