# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_auto_20180911_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='college',
            field=models.CharField(default='XYZ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='conatact_no',
            field=models.IntegerField(default=98267, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='degree',
            field=models.CharField(default='BE', max_length=10),
            preserve_default=False,
        ),
    ]
