# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_auto_20180912_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='conatact_no',
            new_name='contact_no',
        ),
    ]
